general:
  clientUrl: http://localhost:8080
  serviceToken: NlQSNbGvh7EtcpinGnHE9g91

database:
  host: mongo
  databaseName: wizard
  port: 27017
  authEnabled: false
  username:
  password:

messaging:
  enabled: true
  username: guest
  password: guest

jwt:
  secret: gVoYNuEJuGGAQMIaYw43BN3e

mail:
  enabled: false
  name:
  email:
  host:
  port:
  ssl:
  authEnabled:
  username:
  password:

feedback:
  enabled: false
  token:
  owner:
  repo:
