general:
  environment: Production
  serverPort: 3000
  clientUrl: http://localhost:8080
  serviceToken: NlQSNbGvh7EtcpinGnHE9g91
  integrationConfig: integration.yml
  registrationEnabled: true
  publicQuestionnaireEnabled: true
  levelsEnabled: true
  itemTitleEnabled: true

client:
  appTitle:
  appTitleShort:
  welcomeWarning:
  welcomeInfo:

database:
  host: mongo
  databaseName: dsw-server
  port: 27017
  authEnabled: false
  username:
  password:

messaging:
  enabled: false

jwt:
  secret: gVoYNuEJuGGAQMIaYw43BN3e
  version: 1
  expiration: 14

roles:
  defaultRole: DATASTEWARD
  admin: [UM_PERM, ORG_PERM, KM_PERM, KM_UPGRADE_PERM, KM_PUBLISH_PERM, PM_READ_PERM, PM_WRITE_PERM, QTN_PERM, DMP_PERM]
  dataSteward: [KM_PERM, KM_UPGRADE_PERM, KM_PUBLISH_PERM, PM_READ_PERM, PM_WRITE_PERM, QTN_PERM, DMP_PERM]
  researcher: [PM_READ_PERM, QTN_PERM, DMP_PERM]

mail:
  enabled: false
  name:
  email:
  host:
  port:
  ssl:
  username:
  password:

analytics:
  enabled: false
  email:

feedback:
  enabled: false
  token:
  owner:
  repo:
  issueurl:
